### ISSUE TITLE
With your permission Potato.....

### ISSUE THREAD

**Issue by igotfits1** [rmnaderdev/Whitelist-Sync-2#28]
Potato, I come again to ask if its ok for you to share your files with me.
My best bud will update it for me to use on the newer packs, I dont want to use anything else Ive been using your whitelist mod for years and would love to keep it the same.
Can you please grant us that access with your blessing so we can keep using what youve started. I can give you my email or discord or whatever you want.
Im 2pluss2 from curseforge also if that rings a bell.

**Comment by Bodiw** [comment]
Hello! Im the bud @igotfits1 is mentioning
I understand your decision to abandon the project. I also do the same from time to time.
However, would it be possible to opensource 'whitelistsynclib' ? It's a dependency referenced in build.gradle
The maven and the lib seem to be inacessible due to what I guess is an expiry of the SSL certificate at https://rmnad.net/
Wish you best going forward
Bodiw

**Comment by PotatoDotJar** [comment]
@igotfits1 @Bodiw, 

The lib project is on my GitHub https://github.com/PotatoDotJar/Whitelist-Sync-Lib. Everything you need should be on this repo and the lib repo. Feel free to fork and update both projects. I would maintain this project, but I have grown to hate Minecraft Forge over the years. It is not worth my time anymore.

**Comment by Bodiw** [comment]
Google Search didnt reveal anything when I was looking for it. So pardon me asking for it.
Appreciate the effort and ill be sending you a coffee as a thank you gift.
I hope whatever you're working in, it satisfies your desire to create.
Been a pleasure
Bodiw.

**Comment by PotatoDotJar** [comment]
@Bodiw Thank you so much. Let me know if you guys need any help.
